-- Run this in the Supabase SQL editor (Database -> SQL Editor -> New query).

create table if not exists products (
  id bigint generated by default as identity primary key,
  store_id integer not null unique,
  slug text not null,
  name text not null,
  brand text,
  category text,
  sku text,
  description text,
  specs jsonb,
  scrape_interval_hours integer not null default 2 check (scrape_interval_hours between 1 and 168),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_scraped_at timestamptz
);

create table if not exists scrape_runs (
  id uuid primary key default gen_random_uuid(),
  trigger text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  products integer not null default 0,
  ok integer not null default 0,
  failed integer not null default 0,
  note text
);

create table if not exists price_history (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  run_id uuid references scrape_runs(id) on delete set null,
  price numeric(12,2) not null check (price > 0),
  mrp numeric(12,2),
  sale numeric(12,2),
  badge_pct integer,
  currency text not null default 'INR',
  stock integer not null check (stock >= 0),
  in_stock boolean not null,
  pending boolean not null default false,
  rating numeric(3,2),
  rating_count integer,
  seller text,
  delivery_days integer,
  price_format text,
  layout_revision integer,
  scraped_at timestamptz not null default now()
);
create index if not exists price_history_product_time on price_history(product_id, scraped_at desc);

create table if not exists scrape_logs (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  run_id uuid references scrape_runs(id) on delete set null,
  attempt integer not null default 1,
  status text not null check (status in ('success','retried','failed')),
  started_at timestamptz not null,
  finished_at timestamptz not null default now(),
  duration_ms integer,
  error_code text,
  error text,
  details jsonb
);
create index if not exists scrape_logs_product_time on scrape_logs(product_id, started_at desc);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  type text not null check (type in ('price_drop','price_rise','back_in_stock','out_of_stock','structure_change')),
  message text not null,
  old_value text,
  new_value text,
  seen boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists alerts_time on alerts(created_at desc);

-- The backend uses the service_role key, so RLS can stay enabled with no public policies.
alter table products enable row level security;
alter table price_history enable row level security;
alter table scrape_logs enable row level security;
alter table scrape_runs enable row level security;
alter table alerts enable row level security;
